require:
  - esm
  - dotenv/config
  - tests/init.spec.js
spec: './tests/**/*.spec.*'
color: true
reporter: 'mochawesome'
reporter-options: 'reportFilename=index'
timeout: 50000
recursive: true
exit: true